language: android
sudo: required
jdk: oraclejdk8

branches:
  only:
  - dev
  - /^build.*$/

before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

env:
 global:
 - ANDROID_API=28
# - EMULATOR_API_LEVEL=21
 - ANDROID_BUILD_TOOLS_1=28.0.1
 - ANDROID_BUILD_TOOLS_2=28.0.2
 - ANDROID_BUILD_TOOLS_3=28.0.3
 - ADB_INSTALL_TIMEOUT=5 # minutes

android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS_1
 - build-tools-$ANDROID_BUILD_TOOLS_2
 - build-tools-$ANDROID_BUILD_TOOLS_3
 - android-$ANDROID_API
# - android-$EMULATOR_API_LEVEL
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
 - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+

before_install:
 - bundle update
 - bundle install
 - mkdir "$ANDROID_HOME/licenses" || true
 - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
 - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
 - chmod +x gradlew

before_script:
- echo $TRAVIS_TAG
- echo $TRAVIS_COMMIT
- echo $GITHUB_API_TOKEN
#- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#- emulator -avd test -no-skin -no-audio -no-window &
#- android-wait-for-emulator
#- adb shell input keyevent 82 &

script:
- bundle exec fastlane buildDebug;

- if [ "$TRAVIS_PULL_REQUEST" != "false" ];
    then bundle exec fastlane deploy_to_github api_token:$GITHUB_API_TOKEN release_tag:$TRAVIS_TAG release_name:$TRAVIS_TAG release_commit:$TRAVIS_COMMIT release_dir:$TRAVIS_BUILD_DIR/app/build/outputs/apk/**/*.apk;
  fi
- if [ "$TRAVIS_TAG" != "false" ];
    then bundle exec fastlane deploy_to_github api_token:$GITHUB_API_TOKEN release_tag:$TRAVIS_TAG release_name:$TRAVIS_TAG release_commit:$TRAVIS_COMMIT release_dir:$TRAVIS_BUILD_DIR/app/build/outputs/apk/**/*.apk;
  fi
